#SSHJUMPER Config file
#Author Purushothaman
#
#
#   Sample configuration file.. 
#        Need to put it under $HOME/sshjumper/sshjconfig.yml  or update the sshjumper file for specifying different path.


####                     PLEASE READ BELOW BEFORE CONFIGURING SSH JUMPER

#DONT DO
#       Only use alpha,number and underscores for specifying keys (ssh jumper name).
#       DO NOT USE | (PIPE)  ; (SEMICOLON) and , (COMMA)  as separator (DANGER TO USE HERE)
#       CAREFUL with quotes in commands, those might make misbehaviour.
#       CAREFUL with configuration and commands(Those wont be validated before execution).
#DO
#       keys should be intended with tabs
#       hops should be space separated.
#
#   SSH OPTIONS:
#       port of hops should be & prefixed
#       identity file should be ! prefixed
#       
#        Ex: hops: root@10.156.90.197&4742!/home/test/purushkey.pem root@210.56.60.9!/etc/key.pem&5321
#
# Option -i to verify what will happen (To only print the ssh command to be executed, without running).


training:
  hops: root@10.56.10.197&322!/home/test/man
  description: "Training and testing server"
  copytext: {9<jg+(UNp7YU:K&
  terminal: true

primary:
  hops: root@localhost&2231
  terminal: true


#Run free command at the targeted remote
primary_freemem:
  hops: root@localhost&2231
  terminal: true
  command: free -m

projectlive:
  hops: root@10.156.105.153&22
  terminal: true

test:
  hops: root@20.15.90.83&22!/home/purush/test.key mano@127.0.1.2!/etc/key.pem&5321
  terminal: true
